
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 13 15:47:12 GMT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 2;
  public static final int FALSITY = 6;
  public static final int FORALL = 10;
  public static final int TRUTH = 5;
  public static final int EOF = 0;
  public static final int IFF = 3;
  public static final int RBRACKET = 13;
  public static final int ID = 15;
  public static final int COMMA = 14;
  public static final int error = 1;
  public static final int IMPLIES = 8;
  public static final int NOT = 9;
  public static final int EQUALS = 7;
  public static final int LBRACKET = 12;
  public static final int THEREEXISTS = 11;
  public static final int OR = 4;
}

